### ISSUE TITLE
error: Error during startup: Unexpected token T in JSON at position 0

### ISSUE THREAD

**Issue by aganjoo** [pierotofy/node-OpenDroneMap#5] opened 2017-01-24 03:17 UTC
Hello:
Whenever we try to run the service other than in test mode, it always crashes and gives the error message
error: Error during startup: Unexpected token T in JSON at position 0

We tried to create a test config file as well and still get this error
node index.js ----config config.test.json

The error message comes even if you run the command node index.js 

However when we run in the test mode everything works fine and we can communicate to the service from WebODM
root@workspace:~/node-OpenDroneMap# node index.js --test
info: Running in test mode
info: No tasks dump found
info: Checking for orphaned directories to be removed...
info: Server has started on port 3000

Any Guidance would be helpful?

Thanks

**Comment by pierotofy** [comment] 2017-01-24 12:56
Thanks for reporting the issue. I think the problem might be caused by a corrupted `tasks.json`. Please try to remove the node-OpenDroneMap/data directory and then restart the process.

**Comment by pierotofy** [comment] 2017-01-24 13:06
Actually, scratch that, there seems to be a syntax error in the code.

**Comment by pierotofy** [comment] 2017-01-24 13:07
Is https://github.com/OpenDroneMap/OpenDroneMap correctly installed on the same machine as node-OpenDroneMap?

**Comment by pierotofy** [comment] 2017-01-24 13:16
I have added more meaningful error messages when the application starts up. If you update the code to the latest version you'll get a more precise error description.

**Comment by aganjoo** [comment] 2017-01-24 21:15
Thanks for the quick response. Taking the new build helped. There was an issue with ODM install and reinstalling ODM fixed the issue.

**Comment by pierotofy** [comment] 2017-01-24 21:17
Fantastic! I'll close this issue for now.

**Closed by pierotofy** 2017-01-24 21:17 UTC
